# Generated by Django 4.0.4 on 2022-06-17 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_alter_anime_duracion_alter_pelicula_duracion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
