# Generated by Django 4.0.4 on 2022-06-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='nombre_usuario',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avatar',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
