# Generated by Django 4.0.4 on 2022-07-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0005_avatar_nombre_usuario_alter_avatar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='fecha_de_carga',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
