# Generated by Django 4.0.4 on 2022-07-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0008_anime_donde_ver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='duracion',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='donde_ver',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='donde_ver',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
